[package]
name = "console_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.29.1", default-features = false, features = ["default_fonts", "glow"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
